-- Table: public.archive

-- DROP TABLE IF EXISTS public.archive;

CREATE TABLE IF NOT EXISTS public.archive
(
    "archive_ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "hotel_ID" integer NOT NULL,
    "c_SIN" integer NOT NULL,
    "e_SIN" integer NOT NULL,
    check_in date NOT NULL,
    check_out date NOT NULL,
    CONSTRAINT "Archive_pkey" PRIMARY KEY ("archive_ID"),
    CONSTRAINT "c_SIN" FOREIGN KEY ("c_SIN")
        REFERENCES public.customers ("SIN") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "e_SIN" FOREIGN KEY ("e_SIN")
        REFERENCES public.employees ("SIN") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT "hotel_ID" FOREIGN KEY ("hotel_ID")
        REFERENCES public.hotel ("hotelID") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.archive
    OWNER to postgres;
